import type { Metadata } from 'next';
import '../globals.css';
import { Lato } from 'next/font/google';
import Footer from '@/components/layout/footer';
import NextTopLoader from 'nextjs-toploader';
import WhatsAppLink from '@/components/shared/whatsapp-link';

const lato = Lato({ subsets: ['latin'], weight: ['400', '700', '900'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const dynamic = 'force-static';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${lato.className} antialiased`}>
        <NextTopLoader shadow={false} color='#e7d3ae' showSpinner={false} />
        {children}
        <WhatsAppLink />
        <Footer />
      </body>
    </html>
  );
}
