import type { Metadata } from 'next';
import '../globals.css';
import { Montserrat } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';
import Footer from '@/components/layout/footer';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${montserrat.className} antialiased`}>
        <NextTopLoader shadow={false} color='#e7d3ae' showSpinner={false} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
