import type { Metadata } from 'next';
import '../globals.css';
import { Lato } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';
import { PreloadAuthResources } from '@/lib/preload-resources';
import Image from 'next/image';

const lato = Lato({ subsets: ['latin'], weight: ['400', '700', '900'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${lato.className} antialiased`}>
        <PreloadAuthResources />
        <NextTopLoader shadow={false} color='#e7d3ae' showSpinner={false} />
        <section className='grid-cols-2 lg:grid lg:h-screen'>
          <div className='relative max-lg:h-64'>
            <Image
              src='/girl.png'
              alt='Girl with laptop'
              height={300}
              width={300}
              className='h-full w-full object-cover'
              priority
            />
            <div className='absolute left-0 top-0 z-50 h-full w-full bg-black/30' />
          </div>
          <div>{children}</div>
        </section>
      </body>
    </html>
  );
}
